/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qygoedmstvskmstocvsw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5Z29lZG1zdHZza21zdG9jdnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4OTMzMjgsImV4cCI6MjA4MTQ2OTMyOH0.vS-5VOcIZljsge25zC35uiE4LRVSYVRpY-2p0z5F8FY"